### ISSUE TITLE
Mod is crashing with one of the mods i have

### ISSUE THREAD

**Issue by carrotee123** [Kamtheman56/Zelda_Mod#50]
please help Legendary armor is really important to the modpack I'm making but its causing a crash with one of the mods I have installed

[latest.log](https://github.com/user-attachments/files/19617576/latest.log)

[crash-2025-04-05_13.16.21-client.txt](https://github.com/user-attachments/files/19617577/crash-2025-04-05_13.16.21-client.txt)

[modlist.txt](https://github.com/user-attachments/files/19617579/modlist.txt)

**Comment by carrotee123** [comment]
> [@carrotee123](https://github.com/carrotee123) I'll be trying to look into potential fixes and specific causes, but this specific error line appears to be the most concerning: `java.lang.ClassNotFoundException: be.florens.expandability.api.forge.PlayerSwimEvent` and similar, like: `java.lang.NoClassDefFoundError: be/florens/expandability/api/forge/PlayerSwimEvent` `Suppressed: net.minecraftforge.fml.ModLoadingException: Legendary Armory (zeldamod) encountered an error during the common_setup event phase �7java.lang.NoClassDefFoundError: be/florens/expandability/api/forge/PlayerSwimEvent`
> 
> ![Image](https://github.com/user-attachments/assets/73675f52-be1f-4050-82ea-8345d3efd5ad)
> 
> ![Image](https://github.com/user-attachments/assets/11173ed6-44f9-41dc-9f2a-f71982f2a931)
> 
> But also it mentions Glitchcore: `[Render thread/ERROR]: Caught exception during event RegisterEvent dispatch for modid glitchcore` but that could just be because Glitchcore modifies modloading in general, and so it might just be mentioned in errors when present. I'll be checking if removing Glitchcore and associated mods fixes anything, and tweak around from there.
> 
> The main investigation will be around the PlayerSwimEvent issue.

thank you I hope you find a fix

**Comment by carrotee123** [comment]
> [@carrotee123](https://github.com/carrotee123) I'll be trying to look into potential fixes and specific causes, but this specific error line appears to be the most concerning: `java.lang.ClassNotFoundException: be.florens.expandability.api.forge.PlayerSwimEvent` and similar, like: `java.lang.NoClassDefFoundError: be/florens/expandability/api/forge/PlayerSwimEvent` `Suppressed: net.minecraftforge.fml.ModLoadingException: Legendary Armory (zeldamod) encountered an error during the common_setup event phase �7java.lang.NoClassDefFoundError: be/florens/expandability/api/forge/PlayerSwimEvent`
> 
> ![Image](https://github.com/user-attachments/assets/73675f52-be1f-4050-82ea-8345d3efd5ad)
> 
> ![Image](https://github.com/user-attachments/assets/11173ed6-44f9-41dc-9f2a-f71982f2a931)
> 
> But also it mentions Glitchcore: `[Render thread/ERROR]: Caught exception during event RegisterEvent dispatch for modid glitchcore` but that could just be because Glitchcore modifies modloading in general, and so it might just be mentioned in errors when present. I'll be checking if removing Glitchcore and associated mods fixes anything, and tweak around from there.
> 
> The main investigation will be around the PlayerSwimEvent issue.

so I did some more testing the mod by itself crashed so it wasn't glitchcore but then I installed the new update that just came out today 1.4.2 the only difference is it added expand abilities as a requirement and the pack loaded and didn't crash at all wierd

**Comment by MildestToucan** [comment]
> so I did some more testing the mod by itself crashed so it wasn't glitchcore but then I installed the new update that just came out today 1.4.2 the only difference is it added expand abilities as a requirement and the pack loaded and didn't crash at all wierd

Quite odd, I'm not sure as to why, because when using the mod by itself on my own it seems to work fine on my end, even in 1.4.1
I'll be looking to see if anything else can be reproduced.

If it works fine with 1.4.2 that's great though, considering that 1.4.2 also fixed some bugs. Have fun!

**Comment by carrotee123** [comment]
> > so I did some more testing the mod by itself crashed so it wasn't glitchcore but then I installed the new update that just came out today 1.4.2 the only difference is it added expand abilities as a requirement and the pack loaded and didn't crash at all wierd
> 
> Quite odd, I'm not sure as to why, because when using the mod by itself on my own it seems to work fine on my end, even in 1.4.1 I'll be looking to see if anything else can be reproduced.
> 
> If it works fine with 1.4.2 that's great though, considering that 1.4.2 also fixed some bugs. Have fun!

thanks could it be cause I'm using Atlauncher??

**Comment by MildestToucan** [comment]
Launchers like ATLauncher don't typically cause these sorts of issues, but I'll do some testing to see if something is up with that too.

**Comment by carrotee123** [comment]
> Launchers like ATLauncher don't typically cause these sorts of issues, but I'll do some testing to see if something is up with that too.

alrighty thanks I'm gonna enjoy the new update :3
